spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moviebookingapp
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-plarform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: aBHjrujfbsj@$#kmndjd12kkfnrkrnrkms45DNKNNC

  expiration: 3600000
